
const SET_SHOW_APP_OEPN_AD = 'SET_SHOW_APP_OEPN_AD';
const PURCHASE_ITEM = 'PURCHASE_ITEM';
const RESTORE_ITEM = 'RESTORE_ITEM';
const SET_REMOTE_CONFIG = "SET_REMOTE_CONFIG"
const SET_LANGUAGE = "SET_LANGUAGE"
const INITIAL_ROUTE = "INITIAL_ROUTE"
export {
  SET_SHOW_APP_OEPN_AD,  
  RESTORE_ITEM,
  PURCHASE_ITEM,
  SET_REMOTE_CONFIG,
  SET_LANGUAGE,
  INITIAL_ROUTE
};
